---
- name: Install and Configure MySQL
  hosts: mysql_server
  become: true

  tasks:
    - name: Install MySQL server
      package:
        name: "{{ mysql_package }}"
        state: present
      vars:
        mysql_package: "{{ ansible_pkg_mgr == 'yum' | ternary('mysql-server', ansible_pkg_mgr == 'apt' | ternary('mysql-server', '') ) }}"
      tags:
        - mysql

    - name: Start MySQL service and enable it at boot
      service:
        name: "{{ mysql_service }}"
        state: started
        enabled: yes
      vars:
        mysql_service: "{{ ansible_pkg_mgr == 'yum' | ternary('mysqld', ansible_pkg_mgr == 'apt' | ternary('mysql', '') ) }}"
      tags:
        - mysql

    - name: Secure MySQL installation
      expect:
        command: mysql_secure_installation
        responses:
          'Enter password for user root:': ''
          'Press y|Y for Yes, any other key for No:': 'Y'
          'Please enter 0 = LOW, 1 = MEDIUM and 2 = STRONG:': '0'
          'Change the password for root ? ((Press y|Y for Yes, any other key for No) :': 'N'
          'Remove anonymous users? (Press y|Y for Yes, any other key for No) :': 'Y'
          'Disallow root login remotely? (Press y|Y for Yes, any other key for No) :': 'Y'
          'Remove test database and access to it? (Press y|Y for Yes, any other key for No) :': 'Y'
          'Reload privilege tables now? (Press y|Y for Yes, any other key for No) :': 'Y'
      tags:
        - mysql

